apiVersion: v1
kind: Service
metadata:
  name: energy-service
  namespace: estateiq
  labels: { app.kubernetes.io/name: energy-service, estateiq.io/domain: smart-building }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50241, targetPort: 50241 }]
  selector: { app.kubernetes.io/name: energy-service }
