apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: estateiq-aws
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/EstateIQ.git
        revision: HEAD
        directories:
          - path: helm/charts/*
  template:
    metadata:
      name: '{{path.basename}}-aws'
      labels:
        cloud: aws
        estateiq.io/managed-by: argocd
    spec:
      project: estateiq
      source:
        repoURL: https://github.com/prabhat-roy/EstateIQ.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - values-aws.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: estateiq
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true