apiVersion: v1
kind: ConfigMap
metadata:
  name: access-service
  namespace: estateiq
  labels: { app.kubernetes.io/name: access-service, estateiq.io/domain: smart-building }
data:
  LOG_LEVEL: info
  PORT: "50242"
