# AWS overlay for listing-service.
cloud:
  provider: aws
  storageClass: gp3
  ingressClass: alb

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/estateiq-listing-service

podAnnotations:
  iam.amazonaws.com/role: estateiq-listing-service

envFrom:
  - secretRef:
      name: listing-service-aws-secrets
